export const currencyMappings = {
    "Afghanistan": { currency: "Afghan Afghani", fractional: "Pul" },
    "Albania": { currency: "Albanian Lek", fractional: "Qindarka" },
    "Algeria": { currency: "Algerian Dinar", fractional: "Santeem" },
    "Andorra": { currency: "Euro", fractional: "Cent" },
    "Angola": { currency: "Angolan Kwanza", fractional: "Cêntimos" },
    "Antigua and Barbuda": { currency: "East Caribbean Dollar", fractional: "Cents" },
    "Argentina": { currency: "Argentine Peso", fractional: "Centavo" },
    "Armenia": { currency: "Armenian Dram", fractional: "Luma" },
    "Australia": { currency: "Australian Dollar", fractional: "Cents" },
    "Austria": { currency: "Euro", fractional: "Cent" },
    "Azerbaijan": { currency: "Azerbaijani Manat", fractional: "Gəng" },
    "Bahamas": { currency: "Bahamian Dollar", fractional: "Cents" },
    "Bahrain": { currency: "Bahraini Dinar", fractional: "Fils" },
    "Bangladesh": { currency: "Bangladeshi Taka", fractional: "Poisha" },
    "Barbados": { currency: "Barbadian Dollar", fractional: "Cents" },
    "Belarus": { currency: "Belarusian Ruble", fractional: "Kopek" },
    "Belgium": { currency: "Euro", fractional: "Cent" },
    "Belize": { currency: "Belize Dollar", fractional: "Cents" },
    "Benin": { currency: "West African CFA Franc", fractional: "Centime" },
    "Bhutan": { currency: "Bhutanese Ngultrum", fractional: "Chertum" },
    "Bolivia": { currency: "Bolivian Boliviano", fractional: "Centavo" },
    "Bosnia and Herzegovina": { currency: "Bosnia and Herzegovina Convertible Mark", fractional: "Fening" },
    "Botswana": { currency: "Botswana Pula", fractional: "Thebe" },
    "Brazil": { currency: "Brazilian Real", fractional: "Centavo" },
    "Brunei": { currency: "Brunei Dollar", fractional: "Cents" },
    "Bulgaria": { currency: "Bulgarian Lev", fractional: "Stotinka" },
    "Burkina Faso": { currency: "West African CFA Franc", fractional: "Centime" },
    "Burundi": { currency: "Burundian Franc", fractional: "Centime" },
    "Cabo Verde": { currency: "Cape Verdean Escudo", fractional: "Centavo" },
    "Cambodia": { currency: "Cambodian Riel", fractional: "Sen" },
    "Cameroon": { currency: "Central African CFA Franc", fractional: "Centime" },
    "Canada": { currency: "Canadian Dollar", fractional: "Cents" },
    "Central African Republic": { currency: "Central African CFA Franc", fractional: "Centime" },
    "Chad": { currency: "Central African CFA Franc", fractional: "Centime" },
    "Chile": { currency: "Chilean Peso", fractional: "Centavo" },
    "China": { currency: "Chinese Yuan", fractional: "Fen" },
    "Colombia": { currency: "Colombian Peso", fractional: "Centavo" },
    "Comoros": { currency: "Comorian Franc", fractional: "Séntimo" },
    "Congo, Democratic Republic of the": { currency: "Congolese Franc", fractional: "Centime" },
    "Congo, Republic of the": { currency: "Central African CFA Franc", fractional: "Centime" },
    "Costa Rica": { currency: "Costa Rican Colón", fractional: "Centimo" },
    "Croatia": { currency: "Croatian Kuna", fractional: "Lip" },
    "Cuba": { currency: "Cuban Peso", fractional: "Centavo" },
    "Cyprus": { currency: "Euro", fractional: "Cent" },
    "Czech Republic": { currency: "Czech Koruna", fractional: "Haléř" },
    "Denmark": { currency: "Danish Krone", fractional: "Øre" },
    "Djibouti": { currency: "Djiboutian Franc", fractional: "Centime" },
    "Dominica": { currency: "East Caribbean Dollar", fractional: "Cents" },
    "Dominican Republic": { currency: "Dominican Peso", fractional: "Centavo" },
    "Ecuador": { currency: "United States Dollar", fractional: "Cents" },
    "Egypt": { currency: "Egyptian Pound", fractional: "Piastre" },
    "El Salvador": { currency: "United States Dollar", fractional: "Cents" },
    "Equatorial Guinea": { currency: "Central African CFA Franc", fractional: "Centime" },
    "Eritrea": { currency: "Eritrean Nakfa", fractional: "Cent" },
    "Estonia": { currency: "Euro", fractional: "Cent" },
    "Eswatini": { currency: "Swazi Lilangeni", fractional: "Cent" },
    "Ethiopia": { currency: "Ethiopian Birr", fractional: "Santim" },
    "Fiji": { currency: "Fijian Dollar", fractional: "Cents" },
    "Finland": { currency: "Euro", fractional: "Cent" },
    "France": { currency: "Euro", fractional: "Cent" },
    "Gabon": { currency: "Central African CFA Franc", fractional: "Centime" },
    "Gambia": { currency: "Gambian Dalasi", fractional: "Butut" },
    "Georgia": { currency: "Georgian Lari", fractional: "Tetri" },
    "Germany": { currency: "Euro", fractional: "Cent" },
    "Ghana": { currency: "Ghanaian Cedi", fractional: "Ghanaian Gana" },
    "Greece": { currency: "Euro", fractional: "Cent" },
    "Grenada": { currency: "East Caribbean Dollar", fractional: "Cents" },
    "Guatemala": { currency: "Guatemalan Quetzal", fractional: "Centavo" },
    "Guinea": { currency: "Guinean Franc", fractional: "Sonia" },
    "Guinea-Bissau": { currency: "West African CFA Franc", fractional: "Centime" },
    "Guyana": { currency: "Guyanese Dollar", fractional: "Cents" },
    "Haiti": { currency: "Haitian Gourde", fractional: "Centime" },
    "Honduras": { currency: "Honduran Lempira", fractional: "Centavo" },
    "Hungary": { currency: "Hungarian Forint", fractional: "Filler" },
    "Iceland": { currency: "Icelandic Króna", fractional: "Aur" },
    "India": { currency: "Indian Rupee", fractional: "Paise" },
    "Indonesia": { currency: "Indonesian Rupiah", fractional: "Sen" },
    "Iran": { currency: "Iranian Rial", fractional: "Dinar" },
    "Iraq": { currency: "Iraqi Dinar", fractional: "Fils" },
    "Ireland": { currency: "Euro", fractional: "Cent" },
    "Israel": { currency: "Israeli New Shekel", fractional: "Agorot" },
    "Italy": { currency: "Euro", fractional: "Cent" },
    "Jamaica": { currency: "Jamaican Dollar", fractional: "Cent" },
    "Japan": { currency: "Japanese Yen", fractional: "Sen" },
    "Jordan": { currency: "Jordanian Dinar", fractional: "Piastre" },
    "Kazakhstan": { currency: "Kazakhstani Tenge", fractional: "Tiyn" },
    "Kenya": { currency: "Kenyan Shilling", fractional: "Cent" },
    "Kiribati": { currency: "Australian Dollar", fractional: "Cents" },
    "Korea, North": { currency: "North Korean Won", fractional: "Chon" },
    "Korea, South": { currency: "South Korean Won", fractional: "Jeon" },
    "Kuwait": { currency: "Kuwaiti Dinar", fractional: "Fils" },
    "Kyrgyzstan": { currency: "Kyrgyzstani Som", fractional: "Tyiyn" },
    "Laos": { currency: "Lao Kip", fractional: "Att" },
    "Latvia": { currency: "Euro", fractional: "Cent" },
    "Lebanon": { currency: "Lebanese Pound", fractional: "Piastre" },
    "Lesotho": { currency: "Lesotho Loti", fractional: "Sente" },
    "Liberia": { currency: "Liberian Dollar", fractional: "Cents" },
    "Libya": { currency: "Libyan Dinar", fractional: "Dirham" },
    "Liechtenstein": { currency: "Swiss Franc", fractional: "Rappen" },
    "Lithuania": { currency: "Euro", fractional: "Cent" },
    "Luxembourg": { currency: "Euro", fractional: "Cent" },
    "Madagascar": { currency: "Malagasy Ariary", fractional: "Ariary" },
    "Malawi": { currency: "Malawian Kwacha", fractional: "Tambala" },
    "Malaysia": { currency: "Malaysian Ringgit", fractional: "Sen" },
    "Maldives": { currency: "Maldivian Rufiyaa", fractional: "Laari" },
    "Mali": { currency: "West African CFA Franc", fractional: "Centime" },
    "Malta": { currency: "Euro", fractional: "Cent" },
    "Marshall Islands": { currency: "United States Dollar", fractional: "Cents" },
    "Mauritania": { currency: "Mauritanian Ouguiya", fractional: "Koums" },
    "Mauritius": { currency: "Mauritian Rupee", fractional: "Cents" },
    "Mexico": { currency: "Mexican Peso", fractional: "Centavo" },
    "Micronesia": { currency: "United States Dollar", fractional: "Cents" },
    "Moldova": { currency: "Moldovan Leu", fractional: "Ban" },
    "Monaco": { currency: "Euro", fractional: "Cent" },
    "Mongolia": { currency: "Mongolian Tögrög", fractional: "Möngö" },
    "Montenegro": { currency: "Euro", fractional: "Cent" },
    "Morocco": { currency: "Moroccan Dirham", fractional: "Centime" },
    "Mozambique": { currency: "Mozambican Metical", fractional: "Centavo" },
    "Myanmar": { currency: "Burmese Kyat", fractional: "Pya" },
    "Namibia": { currency: "Namibian Dollar", fractional: "Cents" },
    "Nauru": { currency: "Australian Dollar", fractional: "Cents" },
    "Nepal": { currency: "Nepalese Rupee", fractional: "Paisa" },
    "Netherlands": { currency: "Euro", fractional: "Cent" },
    "New Zealand": { currency: "New Zealand Dollar", fractional: "Cents" },
    "Nicaragua": { currency: "Nicaraguan Córdoba", fractional: "Centavo" },
    "Niger": { currency: "West African CFA Franc", fractional: "Centime" },
    "Nigeria": { currency: "Nigerian Naira", fractional: "Kobo" },
    "North Macedonia": { currency: "Macedonian Denar", fractional: "Denari" },
    "Norway": { currency: "Norwegian Krone", fractional: "Øre" },
    "Oman": { currency: "Omani Rial", fractional: "Baisa" },
    "Pakistan": { currency: "Pakistani Rupee", fractional: "Paisa" },
    "Palau": { currency: "United States Dollar", fractional: "Cents" },
    "Palestine": { currency: "Israeli New Shekel", fractional: "Agorot" },
    "Panama": { currency: "Balboa", fractional: "Centavo" },
    "Papua New Guinea": { currency: "Papua New Guinean Kina", fractional: "Toea" },
    "Paraguay": { currency: "Paraguayan Guaraní", fractional: "Céntimo" },
    "Peru": { currency: "Peruvian Sol", fractional: "Céntimo" },
    "Philippines": { currency: "Philippine Peso", fractional: "Centavo" },
    "Poland": { currency: "Polish Zloty", fractional: "Grosz" },
    "Portugal": { currency: "Euro", fractional: "Cent" },
    "Qatar": { currency: "Qatari Rial", fractional: "Dirham" },
    "Romania": { currency: "Romanian Leu", fractional: "Ban" },
    "Russia": { currency: "Russian Ruble", fractional: "Kopek" },
    "Rwanda": { currency: "Rwandan Franc", fractional: "Centime" },
    "Saint Kitts and Nevis": { currency: "East Caribbean Dollar", fractional: "Cents" },
    "Saint Lucia": { currency: "East Caribbean Dollar", fractional: "Cents" },
    "Saint Vincent and the Grenadines": { currency: "East Caribbean Dollar", fractional: "Cents" },
    "Samoa": { currency: "Samoan Tala", fractional: "Sene" },
    "San Marino": { currency: "Euro", fractional: "Cent" },
    "Sao Tome and Principe": { currency: "Dobra", fractional: "Centavo" },
    "Saudi Arabia": { currency: "Saudi Riyal", fractional: "Halalah" },
    "Senegal": { currency: "West African CFA Franc", fractional: "Centime" },
    "Serbia": { currency: "Serbian Dinar", fractional: "Para" },
    "Seychelles": { currency: "Seychellois Rupee", fractional: "Cents" },
    "Sierra Leone": { currency: "Sierra Leonean Leone", fractional: "Cent" },
    "Singapore": { currency: "Singapore Dollar", fractional: "Cents" },
    "Slovakia": { currency: "Euro", fractional: "Cent" },
    "Slovenia": { currency: "Euro", fractional: "Cent" },
    "Solomon Islands": { currency: "Solomon Islands Dollar", fractional: "Cents" },
    "Somalia": { currency: "Somali Shilling", fractional: "Cent" },
    "South Africa": { currency: "South African Rand", fractional: "Cent" },
    "South Korea": { currency: "South Korean Won", fractional: "Jeon" },
    "South Sudan": { currency: "South Sudanese Pound", fractional: "Piastre" },
    "Spain": { currency: "Euro", fractional: "Cent" },
    "Sri Lanka": { currency: "Sri Lankan Rupee", fractional: "Cent" },
    "Sudan": { currency: "Sudanese Pound", fractional: "Piastre" },
    "Suriname": { currency: "Surinamese Dollar", fractional: "Cent" },
    "Sweden": { currency: "Swedish Krona", fractional: "Öre" },
    "Switzerland": { currency: "Swiss Franc", fractional: "Rappen" },
    "Syria": { currency: "Syrian Pound", fractional: "Piastre" },
    "Taiwan": { currency: "New Taiwan Dollar", fractional: "Cent" },
    "Tajikistan": { currency: "Tajik Somoni", fractional: "Diram" },
    "Tanzania": { currency: "Tanzanian Shilling", fractional: "Cent" },
    "Thailand": { currency: "Thai Baht", fractional: "Satang" },
    "Timor-Leste": { currency: "United States Dollar", fractional: "Cents" },
    "Togo": { currency: "West African CFA Franc", fractional: "Centime" },
    "Tonga": { currency: "Tongan Paʻanga", fractional: "Seniti" },
    "Trinidad and Tobago": { currency: "Trinidad and Tobago Dollar", fractional: "Cents" },
    "Tunisia": { currency: "Tunisian Dinar", fractional: "Millime" },
    "Turkey": { currency: "Turkish Lira", fractional: "Kurus" },
    "Turkmenistan": { currency: "Turkmenistani Manat", fractional: "Tenge" },
    "Tuvalu": { currency: "Australian Dollar", fractional: "Cents" },
    "Uganda": { currency: "Ugandan Shilling", fractional: "Cent" },
    "Ukraine": { currency: "Ukrainian Hryvnia", fractional: "Kopiyka" },
    "United Arab Emirates": { currency: "United Arab Emirates Dirham", fractional: "Fils" },
    "United Kingdom": { currency: "British Pound", fractional: "Pence" },
    "United States": { currency: "United States Dollar", fractional: "Cents" },
    "Uruguay": { currency: "Uruguayan Peso", fractional: "Centésimo" },
    "Uzbekistan": { currency: "Uzbekistani Som", fractional: "Tiyn" },
    "Vanuatu": { currency: "Vanuatu Vatu", fractional: "Centime" },
    "Vatican City": { currency: "Euro", fractional: "Cent" },
    "Venezuela": { currency: "Venezuelan Bolívar", fractional: "Céntimo" },
    "Vietnam": { currency: "Vietnamese Dong", fractional: "Hào" },
    "Yemen": { currency: "Yemeni Rial", fractional: "Fils" },
    "Zambia": { currency: "Zambian Kwacha", fractional: "Ngwee" },
    "Zimbabwe": { currency: "United States Dollar", fractional: "Cents" },
};

export const words = [
    "Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven",
    "Eight", "Nine", "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen",
    "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen", "Twenty",
    "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety",
];